FROM node:20-alpine

WORKDIR /app

RUN corepack enable
RUN corepack prepare yarn@4.9.2 --activate

COPY package.json yarn.lock* .yarnrc.yml* ./
COPY apps/api/package.json ./apps/api/package.json
COPY prisma ./prisma

RUN yarn install

RUN yarn workspace @lunchloop/api prisma generate --schema=/app/prisma/schema.prisma

COPY apps/api ./apps/api
COPY packages ./packages

WORKDIR /app/apps/api

EXPOSE 3000

CMD ["yarn", "dev"]